### ISSUE TITLE
How to register

### ISSUE THREAD

**Issue by Ulrar** [syucream/hastodon#1]
Hi,

How exactly do you register ? The quickstart doesn't show. The postApps function takes a HastodonClient, but it doesn't look like it's possible to get one without already having a clientId and a clientSecret.

Thanks

**Comment by Ulrar** [comment]
Passing a HastodonClient with an empty token seems to do the trick, but I had to modify the library to be able to do that. Instead of taking a HastodonClient, I think postApps should just take the mastodon url and construct an empty HastodonClient on the fly.

EDIT : Spoke too soon, it does output an id and a secret, but no way to confirm them apparently. And even when I do generate those by other means and verify them, the mkHastodonClient always return Nothing for some reason, I assume the lib just isn't functional yet.

**Comment by syucream** [comment]
Thanks for your report. I fixed postApps to fetch clientId and clientSecret without OAuth token.
https://github.com/syucream/hastodon/commit/4dfe13aaac3b582737aacf9481532d62aefd7ac6

Can you try it?
