### ISSUE TITLE
Support optional parameters

### ISSUE THREAD

**Issue by as-capabl** [syucream/hastodon#16]
Some methos have optional query parameters or form data like `since_id`, `in_reply_to_id`.
https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md

**Comment by as-capabl** [comment]
I have an implementation for them in my branch.
https://github.com/as-capabl/hastodon/blob/as_capabl/Web/Hastodon/Option.hs
https://github.com/as-capabl/hastodon/blob/1e2ea5d6e3bbcc86f07eaa3bc4230adf4ff1895f/Web/Hastodon.hs#L653

I'm planning to make a PR after some refactoring and adding documentation.

Summary of the specification:
- Options are `Monoid`s. They can be combinded by the `<>` operator like `getStatusesWithOption hd (sinceId x <> maxId y)`. This is a major use of the `Monoid` typeclass as described in  https://en.wikibooks.org/wiki/Haskell/Monoids#Uses
- Some options are polymorphic e.g. both `RangeOption` and `GetStatusOption` accepts `maxId`. My implementation represents them by typeclasses; Both `RangeOption` and `GetStatusOption` has instance of `IsRangeOption` and `maxId`'s type is `IsRangeOption a => Int -> a`

**Comment by Ulrar** [comment]
Hey,

Any ETA on this ? I've been using a modified version of Hastodon in which I added some functions to add visibility to toots, reply_id and things like that, but keeping that up to date is annoying, it'd be great if Hastodon itself could get that support.

**Comment by as-capabl** [comment]
I am sorry to have kept you waiting.
I’m (also) working to catch up with the newest change.
It will finish at May 7.
