### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by Ulrar** [syucream/hastodon#2]
Hi,

Any chance you'd implement the streaming API (maybe in a similar way twitter-conduit did it) ?
If not I'll try to get on that and maybe make you a PR, but I'll have to understand how conduits work first so that may take a while :)

**Comment by swizzard** [comment]
I'm working on an implementation for this: https://github.com/swizzard/hastodon/tree/swizzard-streaming
It's a bit more complicated than I hoped it would be; I'd love some help with it if you or @syucream have time.

**Comment by swizzard** [comment]
https://github.com/syucream/hastodon/pull/19

**Comment by syucream** [comment]
Fixed by https://github.com/syucream/hastodon/pull/19. Its supported by `0.4.0`
