### ISSUE TITLE
ids should be represented by different types

### ISSUE THREAD

**Issue by swizzard** [syucream/hastodon#26]
currently, `HastodonId` represents status ids, account ids, and media ids. it would be more informative to have separate types for each of these. additional type-safety could be guaranteed by having these be `newtype`s.

the downside of this would be a little more noise in the API functions that use `replace`, but we could avoid this by using a custom function `IsString a => a -> a -> a -> a` and deriving `IsString` for our newtypes.

**Comment by syucream** [comment]
It might be fixed by https://github.com/syucream/hastodon/pull/27
