### ISSUE TITLE
Non-ASCII character handling

### ISSUE THREAD

**Issue by as-capabl** [syucream/hastodon#4]
http://qiita.com/satosystems/items/e07e9907e4da9ab853fc

非ASCIIのStringに対してChar8.packを呼ぶと、文字化けが発生します。
現状、postStatus等Stringをpostする関数は、非ASCII文字列を渡すと正常に動作しないようです。

**Comment by syucream** [comment]
It looks be fixed at https://github.com/syucream/hastodon/pull/6
